### ISSUE TITLE
QMK Setup

### ISSUE THREAD

**Issue by xervon** [dnaq/plover-machine-hid#1]
How would you go about using this in a QMK keymap?

Your README seems to suggest that QMK already has support but I can't seem to find any reference to it in QMK itself.

**Comment by dnaq** [comment]
You need to use my plover hid branch of qmk. I haven’t opened a pull
request yet.

Then you need to set `PLOVER_HID_ENABLE = yes` in your rules.mk and set up
a keymap with `PLV_XX` keycodes (after including plover_hid.h).

**Comment by xervon** [comment]
I hadn't seen that branch. Thanks.

**Comment by stites** [comment]
Posting the zmk link for posterity: https://github.com/dnaq/zmk/tree/plover-hid-hog-attempt
