### ISSUE TITLE
It'd be great if this was in the plugin manager.

### ISSUE THREAD

**Issue by kybernetikos** [dnaq/plover-machine-hid#4]
The latest Plovers ship with a plugin manager which makes installing plugins a lot easier.

As far as I can tell, the only requirement is that the plugin is published to PyPI, then we can submit a PR for this repository https://github.com/openstenoproject/plover_plugins_registry 

This plugin has been really good to use with the corne-ish zen that I have. We've been chatting about it on the steno-talk channel in the lowprokb.ca discord.

**Comment by dnaq** [comment]
It would. The main issue is that the plugin isn’t self-contained, it requires a non python library to be installed and available on the host, so just having it in the plugin manager would probably lead to quite a bit of confusion for many people.

I tried getting plover to open up to adding it to the main plover distribution quite a while ago, but that discussion never took off.

**Comment by binary-adam** [comment]
Thanks for letting me know. That is a shame. Is the external library that it needs libhidapi-hidraw.so.0?  I noticed that I had to install it on one of the machines I installed the plugin on.

Thanks for the plugin anyway.

**Comment by dnaq** [comment]
Yeah, that’s the library in question (on linux). No worries, hope you’ll have good use for it, it would have been nice to have gotten it into plover core, and that would probably have helped with getting it into zmk/qmk as well, but it is what it is.
